version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port

    volumes:
      - /root/apps/nginx/data:/data
      - /root/apps/nginx/letsencrypt:/etc/letsencrypt
    network_mode: bridge